### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by TheDIGuy** [Jorengarenar/RedditOldRedesignedDark#1]
Hey! It's the guy from reddit. Just filing an issue.

I don't know if it's of any help but here's the link to the Imgur album: https://imgur.com/a/oeCrIQC
Thanks!

**Comment by Jorengarenar** [comment]
Those problems should disappear, when you disallow "_custom themes_" in [preferences settings](https://old.reddit.com/prefs).

**Comment by TheDIGuy** [comment]
Hey @Jorengarenar would you mind deleting this issue? I'm trying to clean up my github account, and since you have the solution in the readme this issue seems to be useless. Thanks!
